"""
pista.py – Track image to tile map converter
─────────────────────────────────────────────
Reads pista.png and converts it to a JavaScript tile map (mapa_gerado.js)
that the simulation loads directly.

Tile encoding:
  0 = road        (white / light pixels)
  1 = wall        (dark / black pixels)
  2 = finish line (green pixels   — R<100, G>150, B<100)
  3 = spawn point (blue pixels    — R<80,  G<80,  B>200)

How to use:
  1. Draw (or edit) pista.png using any image editor.
  2. Run:  python pista.py
  3. Reload index.html in the browser — the new map is used automatically.

Requirements:
  pip install pillow numpy
"""

from PIL import Image
import numpy as np

# ── Configuration ──────────────────────────────────────────────────────────
IMAGE_PATH  = "pista.png"
OUTPUT_PATH = "mapa_gerado.js"
MAP_WIDTH   = 160   # tiles (resize target)
MAP_HEIGHT  = 80    # tiles
TILE_SIZE   = 10    # pixels per tile in the simulation

# ── Load & resize ──────────────────────────────────────────────────────────
img    = Image.open(IMAGE_PATH).convert("RGB")
img    = img.resize((MAP_WIDTH, MAP_HEIGHT), Image.LANCZOS)
pixels = np.array(img)


def pixel_to_tile(r, g, b):
    """Map an RGB pixel to a tile value (0–3)."""
    if b > 200 and r < 80  and g < 80:   return 3   # spawn  (blue)
    if r < 80  and g < 80  and b < 80:   return 1   # wall   (black)
    if g > 150 and r < 100 and b < 100:  return 2   # finish (green)
    return 0                                         # road   (everything else)


# ── Build tile matrix ──────────────────────────────────────────────────────
grid = [
    [pixel_to_tile(r, g, b) for (r, g, b) in row]
    for row in pixels
]

# ── Quick sanity preview ───────────────────────────────────────────────────
print("First 5 rows (first 20 cols):")
for row in grid[:5]:
    print(row[:20])

# ── Write JS output ────────────────────────────────────────────────────────
with open(OUTPUT_PATH, "w") as f:
    f.write(f"// Auto-generated by pista.py – do not edit manually.\n")
    f.write(f"// Tile size: {TILE_SIZE}px  |  Map: {MAP_WIDTH}×{MAP_HEIGHT} tiles\n")
    f.write(f"// Values: 0=road  1=wall  2=finish  3=spawn\n\n")
    f.write(f"let tileSize = {TILE_SIZE};\n")
    f.write("let mapa = [\n")
    for row in grid:
        f.write("  [" + ",".join(map(str, row)) + "],\n")
    f.write("];\n")

print(f"\n✅  Map saved to {OUTPUT_PATH}  ({MAP_WIDTH}×{MAP_HEIGHT} tiles, tileSize={TILE_SIZE}px)")
